### ISSUE TITLE
The "NativeNotificationService" issue

### ISSUE THREAD

**Issue by WitoldSlawko** [LenonLopez/angular-notice#2]
Hi @LenonLopez .

As I wrote at: https://github.com/alexcastillo/ng2-notifications/issues/22, the NativeNotificationService should be also include in the app.module.ts for a proper npm package work.

What I mean, is the fact, that the line: 
import { NativeNotificationService } from 'angular-notice/lib/native-notification.service';
should also be included at the top of app.module.ts and therefore the NativeNotificationService should be place there into it's providers array, so:

at ./app.module.ts

import { NativeNotificationService } from 'angular-notice/lib/native-notification.service';

@NgModule({
  ...
  providers: [NativeNotificationService],
 ...
});

where the three dots (...) are the other properties needed inside @NgModule.

Anyway, good job for make an alternative for unusable ng2-notifications package for Angular2+(4).

:)

**Comment by LenonLopez** [comment]
@WitoldSlawko  Thank you for the feedback. Though you are correct that the service needs to be in the providers array, this is only the case if you are importing the **service** directly into your app's module. The project is currently built as a **module**  (NotificationsModule), which has the service within its own providers array. Because this module has the service within its providers, there is no need to add the service to your specific app's providers array. Just import the module as stated in the Readme.  The issue you present lies in the difference in how we are importing the service. With all that said, I reserve the right to be mistaken : )
